# this workflow doesn't use GH apps nor PATs, but the GITHUB_TOKEN
# provided by pipeline env itself
name: Publish Python ğŸ distribution ğŸ“¦ to PyPI and TestPyPI

on:
  workflow_call:
    #inputs:
      #config-path:
        #required: true
        #type: string
    #secrets:
      #token:
        #required: true

#permissions:
  #contents: write

jobs:
  build-test:
    name: Build distribution ğŸ“¦
    runs-on: ubuntu-latest
    # decrease our perms:
    permissions:
      contents: read

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: committer
        run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"
      - run: echo "committer string is ${{ steps.committer.outputs.string }}"
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - run: |
          git add .
          git commit -m "Auto-generated changes"
          git push






    #steps:
    #- uses: actions/checkout@v5
      #with:
        #persist-credentials: false
    #- name: Set up Python
      #uses: actions/setup-python@v5
      #with:
        #python-version: "3.x"
    #- name: install dev/test deps
      #run: |
        #pip install '.[dev]'
    ##- name: Lint
      ##run: |
        ##command -v ruff >/dev/null && echo have ruff
        ### stop the build if there are Python syntax errors or undefined names:
        ##ruff check --select=E9,F63,F7,F82
        ### exit-zero treats all errors as warnings:
        ##ruff check --exit-zero --statistics
    #- name: Test
      #run: |
        #pytest
    #- name: Install pypa/build & build the binary wheel/src tarball
      #run: |
        #pip install build
        #python -m build
    #- name: Store the distribution packages
      #uses: actions/upload-artifact@v4
      #with:
        #name: release-dist
        #path: dist/

  #version-tag-changelog:
    #name: Version & tag the release
    #if: ${{ github.ref == 'refs/heads/master' }}
    #needs:
    #- build-test
    #runs-on: ubuntu-latest
    ##not needed, as calling workflow already provides write perms:
    ##permissions:
      ##contents: write

    #steps:
    #- uses: actions/checkout@v5
      #with:
        #persist-credentials: true
    #- name: Configure git
      #run: |
        #git config --global user.name 'workflow-bot'
        #git config --global user.email 'ci@github'

    #- name: Install zestreleaser & cut a tag
      #run: |
        #pip install zest.releaser
        #fullrelease --no-input

  ## note publish to pypi cannot be ran from reusable workflows, follow
  ## https://github.com/pypa/gh-action-pypi-publish/issues/166 for more details
  ##publish-to-pypi:
    ##name: >-
      ##Publish Python ğŸ distribution ğŸ“¦ to PyPI
    ##if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    ##needs:
    ##- build-test
    ##runs-on: ubuntu-latest
    ##environment:
      ##name: pypi
      ###url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name; optional
    ##permissions:
      ##id-token: write  # IMPORTANT: mandatory for trusted publishing

    ##steps:
    ##- name: Download all the dists
      ##uses: actions/download-artifact@v4
      ##with:
        ##name: release-dist
        ##path: dist/
    ##- name: Publish distribution ğŸ“¦ to PyPI
      ##uses: pypa/gh-action-pypi-publish@release/v1

  ##publish-to-testpypi:
    ##name: Publish Python ğŸ distribution ğŸ“¦ to TestPyPI
    ##needs:
    ##- build-test
    ##runs-on: ubuntu-latest

    ##environment:
      ##name: testpypi
      ###url: https://test.pypi.org/p/<package-name>; optional

    ##permissions:
      ##id-token: write  # IMPORTANT: mandatory for trusted publishing

    ##steps:
    ##- name: Download all the dists
      ##uses: actions/download-artifact@v4
      ##with:
        ##name: release-dist
        ##path: dist/
    ##- name: Publish distribution ğŸ“¦ to TestPyPI
      ##uses: pypa/gh-action-pypi-publish@release/v1
      ##with:
        ##repository-url: https://test.pypi.org/legacy/
